package com.maven.Bean;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.Date;

@Component
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * ID
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Name
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 姓名
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Job_number
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 工号
     */
    private String jobNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Password
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 密码
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.MobilePhone
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 移动电话
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.Email
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 邮件
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IsDeleted
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 是否已删除,默认未删除
     */
    private Integer isdeleted=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IsSuperAdmin
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 是否是超管,默认不是
     */
    private Integer issuperadmin=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CreateUserID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 账号创建人
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CreateUserTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 创建时间
     */
    private LocalDateTime createusertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.IsLock
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 是否锁定 默认未锁定
     */
    private Integer islock=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ExpirationTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 过期时间
     */
    private LocalDateTime expirationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.DeptID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     * 部门ID
     */
    private Integer deptid;

    /**
     * 存在session的验证码
     */
    private String verifiCode=null;

    public String getVerifiCode() {
        return verifiCode;
    }

    public void setVerifiCode(String verifiCode) {
        this.verifiCode = verifiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ID
     *
     * @return the value of tb_user.ID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ID
     *
     * @param id the value for tb_user.ID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Name
     *
     * @return the value of tb_user.Name
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Name
     *
     * @param name the value for tb_user.Name
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Job_number
     *
     * @return the value of tb_user.Job_number
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Job_number
     *
     * @param jobNumber the value for tb_user.Job_number
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber == null ? null : jobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Password
     *
     * @return the value of tb_user.Password
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Password
     *
     * @param password the value for tb_user.Password
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MobilePhone
     *
     * @return the value of tb_user.MobilePhone
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MobilePhone
     *
     * @param mobilephone the value for tb_user.MobilePhone
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.Email
     *
     * @return the value of tb_user.Email
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.Email
     *
     * @param email the value for tb_user.Email
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IsDeleted
     *
     * @return the value of tb_user.IsDeleted
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IsDeleted
     *
     * @param isdeleted the value for tb_user.IsDeleted
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IsSuperAdmin
     *
     * @return the value of tb_user.IsSuperAdmin
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public Integer getIssuperadmin() {
        return issuperadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IsSuperAdmin
     *
     * @param issuperadmin the value for tb_user.IsSuperAdmin
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setIssuperadmin(Integer issuperadmin) {
        this.issuperadmin = issuperadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CreateUserID
     *
     * @return the value of tb_user.CreateUserID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CreateUserID
     *
     * @param createuserid the value for tb_user.CreateUserID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CreateUserTime
     *
     * @return the value of tb_user.CreateUserTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */

    public LocalDateTime getCreateusertime() {
        return createusertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CreateUserTime
     *
     * @param createusertime the value for tb_user.CreateUserTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */

    public void setCreateusertime(LocalDateTime createusertime) {
        this.createusertime = createusertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IsLock
     *
     * @return the value of tb_user.IsLock
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public Integer getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IsLock
     *
     * @param islock the value for tb_user.IsLock
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setIslock(Integer islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ExpirationTime
     *
     * @return the value of tb_user.ExpirationTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public LocalDateTime getExpirationtime() {
        return expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ExpirationTime
     *
     * @param expirationtime the value for tb_user.ExpirationTime
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setExpirationtime(LocalDateTime expirationtime) {
        this.expirationtime = expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.DeptID
     *
     * @return the value of tb_user.DeptID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.DeptID
     *
     * @param deptid the value for tb_user.DeptID
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}