package com.maven.Mapper;

import com.maven.Bean.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Mon Aug 22 13:45:23 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据工号jobnumber查询用户信息
     */
    User selectByJobnumber(@Param("jobnumber") String jobnumber);

    /**
     * 根据工号和密码验证是否正确，用于登录验证
     * @return
     */
    List<User> selectByJobAndPassword(@Param("jobnumber") String jobnumber,@Param("password")String password);
}